variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "ansible-sg-id" {}
variable "keys" {}
variable "prv_key" {}
variable "HAproxy1_IP" {}
variable "HAproxy2_IP" {}
variable "master1_IP" {}
variable "master2_IP" {}
variable "master3_IP" {}
variable "worker1_IP" {}
variable "worker2_IP" {}
variable "worker3_IP" {}
variable "ansible_server" {}
variable "bastion-host" {}
