variable "project-name" {}
variable "profile-name" {}
variable "region" {}
variable "vpc_instance_tenancy" {}
variable "all-cidr" {}
variable "cidr_block_vpc" {}
variable "pub_sn1_cidr_block" {}
variable "pub_sn2_cidr_block" {}
variable "pub_sn3_cidr_block" {}
variable "priv_sn1_cidr_block" {}
variable "priv_sn2_cidr_block" {}
variable "priv_sn3_cidr_block" {}
variable "az1" {}
variable "az2" {}
variable "az3" {}
variable "instance_type2" {}
variable "instance_type" {}
variable "ami-redhat" {}
variable "ubuntu-ami" {}
variable "instance-count" {}
variable "domain_name" {}
variable "domain_name2" {}
variable "grafana_domain_hosted_zone" {}
variable "prometheus_domain_hosted_zone" {}
variable "stage_domain_hosted_zone" {}
variable "prod_domain_name" {}