---
- hosts: localhost
  become: true

  tasks:

    - name: Check if Application Repo exists
      stat:
        path: /home/ubuntu/my-gradleproject
      register: repo_exists

    - name: Clone or Update Application Repo
      git:
        repo: https://github.com/kogunniyi/my-gradleproject.git
        dest: /home/ubuntu/my-gradleproject
      when: not repo_exists.stat.exists

    - name: Updating Application Repo
      shell:
        cmd: git pull
        chdir: /home/ubuntu/my-gradleproject
      when: repo_exists.stat.exists

    - name: Building Application war Artifact
      command: ./gradlew build
      args: 
        chdir: /home/ubuntu/my-gradleproject

    - name: Building Docker image
      command: docker build -t kogunniyi/app .
      args:
        chdir: /home/ubuntu/my-gradleproject

    - name: Login into DockerHub
      command: docker login -u kogunniyi -p Secur!ty50@
    
    - name: Push image to Dockerhub
      command: docker push kogunniyi/app

    - name: Applying Latest Features to stage-shop
      command: sudo su -c 'kubectl apply -f /home/ubuntu/my-gradleproject/k8s-spring-boot-deployment.yml' ubuntu

    - name: Restart Application
      command: sudo su -c 'kubectl rollout restart deployment/hello-world' ubuntu
      ignore_errors: true