variable "subnets" {}
variable "sg" {}
variable "vpc_id" {}
variable "vpc" {}
variable "certificate_arn" {}
variable "instance1" {}
variable "instance2" {}
variable "instance3" {}
variable "name" {}
variable "name2" {}