# Jenkins variables
variable "instance_type_t2" {}
variable "keypair_name" {}
variable "prt_sn1" {}
variable "jenkins_name" {}
variable "jenkins_sg" {}
variable "elb_name" {}
variable "subnet_id2" {}
variable "ami-redhat" {}