variable "domain_name" {}
variable "domain_name2" {}
variable "prod_domain_name" {}
variable "stage_domain_hosted_zone" {}
variable "prometheus_domain_hosted_zone" {}
variable "grafana_domain_hosted_zone" {}
variable "prod-lb-dns-name" {}
variable "prod-lb-zone-id" {}
variable "stage-lb-dns-name" {}
variable "stage-lb-zone-id" {}
variable "prometheus-lb-dns-name" {}
variable "prometheus-lb-zone-id" {}
variable "grafana-lb-dns-name" {}
variable "grafana-lb-zone-id" {}